package pl.aniolstroz.config;

import java.time.Clock;
import java.time.Instant;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.boot.info.BuildProperties;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RestController;
import pl.aniolstroz.contracts.api.StatusApi;

/** GET /api/status; the interface is generated from contracts/openapi.yaml (CON-03). */
@RestController
class StatusController implements StatusApi {

    private final AppProperties properties;
    private final String version;
    private final Instant startedAt;

    StatusController(AppProperties properties, ObjectProvider<BuildProperties> buildProperties, Clock clock) {
        this.properties = properties;
        // build-info is generated by Maven; fall back to "dev" when running from an IDE without it
        BuildProperties build = buildProperties.getIfAvailable();
        this.version = build != null ? build.getVersion() : "dev";
        this.startedAt = clock.instant();
    }

    @Override
    public ResponseEntity<StatusResponse> getStatus() {
        return ResponseEntity.ok(new StatusResponse(properties.mode(), version, startedAt));
    }
}
