package pl.aniolstroz.config;

import java.time.Clock;
import java.time.Instant;
import org.springframework.boot.info.BuildProperties;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
class StatusController {

    private final AppProperties properties;
    private final String version;
    private final Instant startedAt;

    StatusController(AppProperties properties, ObjectProvider<BuildProperties> buildProperties, Clock clock) {
        this.properties = properties;
        // build-info is generated by Maven; fall back to "dev" when running from an IDE without it
        BuildProperties build = buildProperties.getIfAvailable();
        this.version = build != null ? build.getVersion() : "dev";
        this.startedAt = clock.instant();
    }

    @GetMapping("/api/status")
    StatusResponse status() {
        return new StatusResponse(properties.mode(), version, startedAt);
    }
}
